#name: flutter_web_landingpage
#description: An app built using Flutter for web
#
#environment:
#  # You must be using Flutter >=1.5.0 or Dart >=2.3.0
#  sdk: '>=2.3.0-dev.0.1 <3.0.0'
#
#dependencies:
#  flutter_web: any
#  flutter_web_ui: any
#
#dev_dependencies:
#  build_runner: ^1.4.0
#  build_web_compilers: ^2.0.0
#  pedantic: ^1.0.0
#
#dependency_overrides:
#  flutter_web:
#    git:
#      url: https://github.com/flutter/flutter_web
#      path: packages/flutter_web
#  flutter_web_ui:
#    git:
#      url: https://github.com/flutter/flutter_web
#      path: packages/flutter_web_ui

name: rajaee_web_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  http: ^1.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
#  flutter_secure_storage: ^8.0.0

  salomon_bottom_bar: ^3.3.1
  fluttericon: ^2.0.0
  carousel_slider: ^5.0.0
  persian_datetime_picker: ^3.0.2
  qr_flutter: ^4.0.0
  fl_chart: ^0.69.2
  fast_cached_network_image: ^1.1.1
  shimmer: ^3.0.0
  shared_preferences: ^2.0.18
  intl: ^0.20.1
  persian_number_utility: ^1.1.3
  overlay_loader_with_app_icon: ^0.0.3
  flutter_launcher_icons: ^0.14.2
  url_launcher: ^6.1.11
  lazy_load_scrollview: 1.3.0
  get_it: ^8.0.2

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Vazirmatn
      fonts:
        - asset: assets/fonts/Vazirmatn-RD-Light.ttf
    - family: Sahel
      fonts:
        - asset: assets/fonts/Sahel.ttf
    - family: Digital
      fonts:
        - asset: assets/fonts/Digital Dismay.otf
    - family: Linearicons
      fonts:
        - asset: assets/fonts/Linearicons-Free.ttf
    - family: Titr
      fonts:
        - asset: assets/fonts/Titr.ttf

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/ic_launcher.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/ic_launcher.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"